# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - puzzlepro

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_a4ec6a4609d142f994caa248d99848d0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1ad130147d1e40319f26b923d8afd1fa }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_a4ec6a4609d142f994caa248d99848d0 }}/dhrumilpatel30/puzzlepro-image:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'puzzlepro'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_88b9b0651a7d4c8189b6a2e0676b33c5 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_a4ec6a4609d142f994caa248d99848d0 }}/dhrumilpatel30/puzzlepro-image:${{ github.sha }}'